spring.application.name=MedicalApplication

spring.datasource.url=jdbc:mysql://localhost:3306/medicalapp_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aplicatie.medicala.info@gmail.com
spring.mail.password=vccg xzgq svyi bxvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# optional (debug)
spring.mail.properties.mail.debug=true

# de la cine pleaca emailul
app.mail.from=MedicalApp <aplicatie.medicala.info@gmail.com>

jwt.secret=MedicalAppSecretKeyForJWTToken2025VerySecureAndLongKey123456789_Extra_Extra_Extra_1234567890

jwt.expiration=86400000